const userList = [
    {
      email: "user1@example.com",
      dateJoined: "2022-01-15",
      userName: "user1",
      displayName: "User One",
      profilePicture: "https://example.com/user1.jpg",
      followers: 1000,
      following: 500,
      bio: "Hello, I'm User One!",
      banner: "https://example.com/user1_banner.jpg",
    },
    {
      email: "user2@example.com",
      dateJoined: "2022-03-05",
      userName: "user2",
      displayName: "User Two",
      profilePicture: "https://example.com/user2.jpg",
      followers: 2000,
      following: 700,
      bio: "Hey there! I'm User Two.",
      banner: "https://example.com/user2_banner.jpg",
    },
    {
      email: "user3@example.com",
      dateJoined: "2022-06-10",
      userName: "user3",
      displayName: "User Three",
      profilePicture: "https://example.com/user3.jpg",
      followers: 500,
      following: 300,
      bio: "Nice to meet you! I'm User Three.",
      banner: "https://example.com/user3_banner.jpg",
    },
    {
      email: "user4@example.com",
      dateJoined: "2022-09-20",
      userName: "user4",
      displayName: "User Four",
      profilePicture: "https://example.com/user4.jpg",
      followers: 1500,
      following: 900,
      bio: "Greetings! I'm User Four.",
      banner: "https://example.com/user4_banner.jpg",
    },
    {
      email: "user5@example.com",
      dateJoined: "2023-01-01",
      userName: "user5",
      displayName: "User Five",
      profilePicture: "https://example.com/user5.jpg",
      followers: 800,
      following: 400,
      bio: "Hi, I'm User Five!",
      banner: "https://example.com/user5_banner.jpg",
    },
    {
      email: "user6@example.com",
      dateJoined: "2023-03-15",
      userName: "user6",
      displayName: "User Six",
      profilePicture: "https://example.com/user6.jpg",
      followers: 3000,
      following: 1200,
      bio: "Hey, nice to meet you! I'm User Six.",
      banner: "https://example.com/user6_banner.jpg",
    },
    {
      email: "user7@example.com",
      dateJoined: "2023-05-10",
      userName: "user7",
      displayName: "User Seven",
      profilePicture: "https://example.com/user7.jpg",
      followers: 700,
      following: 200,
      bio: "Hello! I'm User Seven.",
      banner: "https://example.com/user7_banner.jpg",
    },
    {
      email: "user8@example.com",
      dateJoined: "2023-07-01",
      userName: "user8",
      displayName: "User Eight",
      profilePicture: "https://example.com/user8.jpg",
      followers: 200,
      following: 100,
      bio: "Greetings! I'm User Eight.",
      banner: "https://example.com/user8_banner.jpg",
    },
    {
      email: "user9@example.com",
      dateJoined: "2023-09-18",
      userName: "user9",
      displayName: "User Nine",
      profilePicture: "https://example.com/user9.jpg",
      followers: 1200,
      following: 800,
      bio: "Hi there! I'm User Nine.",
      banner: "https://example.com/user9_banner.jpg",
    },
    {
      email: "user10@example.com",
      dateJoined: "2024-01-05",
      userName: "user10",
      displayName: "User Ten",
      profilePicture: "https://example.com/user10.jpg",
      followers: 2500,
      following: 1500,
      bio: "Hey! I'm User Ten.",
      banner: "https://example.com/user10_banner.jpg",
    },
]
  
const tweets = [
  {
    tweetId: 1,
    tweeter: "user1",   
    timeSent: '2023-06-26T09:30:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 5,
    quoteAmount: 22,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 2,
    tweeter: "user2",   
    timeSent: '2023-06-26T10:15:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 10,
    quoteAmount: 32,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 3,
    tweeter: "user3",   
    timeSent: '2023-06-26T11:00:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 25,
    quoteAmount: 82,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 4,
    tweeter: "user4",   
    timeSent: '2023-06-26T12:30:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 15,
    quoteAmount: 52,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 5,
    tweeter: "user5",   
    timeSent: '2023-06-26T14:00:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 50,
    quoteAmount: 12,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 6,
    tweeter: "user6",   
    timeSent: '2023-06-26T15:45:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 8,
    quoteAmount: 12,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 7,
    tweeter: "user7",   
    timeSent: '2023-06-26T16:30:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 12,
    quoteAmount: 42,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 8,
    tweeter: "user8",   
    timeSent: '2023-06-26T18:00:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 30,
    quoteAmount: 92,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 9,
    tweeter: "user9",   
    timeSent: '2023-06-26T19:30:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 18,
    quoteAmount: 62,
    replyingTo: null,
    level: 0,
    parentTweet: null
  },
  {
    tweetId: 10,
    tweeter: "user10",   
    timeSent: '2023-06-26T21:00:00Z',
    tweetText: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore id ab dolorum reprehenderit pariatur soluta laboriosam libero magni, voluptate, temporibus nesciunt amet incidunt perferendis eligendi optio hic alias aliquam porro.",
    likes: {},
    retweetCount: 20,
    quoteAmount: 72,
    replyingTo: null,
    level: 0,
    parentTweet: null
  }
]

const tweetMap = new Map(tweets.map(tweet => [tweet.tweetId, tweet]));

// Store the tweet map in the localStorage
localStorage.setItem('tweetMap', JSON.stringify(Array.from(tweetMap)));
  
export { userList, tweets }